name: PR
on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.8
        with:
          runTests: false

  lint:
    needs: [install-dependencies]
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.8
        with:
          runTests: false
      - name: lint
        run: yarn lint

  cypress-e2e-test:
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cypress e2e tests 🧪
        uses: cypress-io/github-action@v5.0.8
        with:
          start: yarn start
          wait-on: 'http://localhost:8080'
          config-file: cypress/config/local.config.js
          browser: chrome
          record: true
          parallel: true
          group: local-e2e-tests
          tag: local-e2e-tests

  cypress-ct-test:
    strategy:
      fail-fast: false
      matrix:
        machines: [1, 2]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cypress component tests 🧪
        uses: cypress-io/github-action@v5.0.8
        with:
          component: true
          browser: chrome
          record: true
          parallel: true
          group: ct-tests
          tag: ct-tests
